var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/practice/generate/route.js")
R.c("server/chunks/[root-of-the-server]__307c58c3._.js")
R.c("server/chunks/[root-of-the-server]__6010f445._.js")
R.c("server/chunks/[root-of-the-server]__c48dbbd3._.js")
R.c("server/chunks/[root-of-the-server]__7daa31a4._.js")
R.c("server/chunks/[root-of-the-server]__e6c2f3ce._.js")
R.c("server/chunks/node_modules_zod_v4_classic_external_fa90cebf.js")
R.c("server/chunks/node_modules_next_f2da0d3e._.js")
R.c("server/chunks/_next-internal_server_app_api_practice_generate_route_actions_c271c21b.js")
R.m(89034)
module.exports=R.m(89034).exports
