var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/analyze/route.js")
R.c("server/chunks/[root-of-the-server]__307c58c3._.js")
R.c("server/chunks/node_modules_zod_v4_classic_external_fa90cebf.js")
R.c("server/chunks/[root-of-the-server]__8dc5ab6f._.js")
R.c("server/chunks/[root-of-the-server]__4b9c5815._.js")
R.c("server/chunks/[root-of-the-server]__7daa31a4._.js")
R.c("server/chunks/[root-of-the-server]__6010f445._.js")
R.c("server/chunks/node_modules_next_f2da0d3e._.js")
R.c("server/chunks/_next-internal_server_app_api_analyze_route_actions_487cf259.js")
R.m(26794)
module.exports=R.m(26794).exports
