var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/reanswer/route.js")
R.c("server/chunks/[root-of-the-server]__307c58c3._.js")
R.c("server/chunks/node_modules_zod_v4_classic_external_fa90cebf.js")
R.c("server/chunks/[root-of-the-server]__2fdd6928._.js")
R.c("server/chunks/[root-of-the-server]__4b9c5815._.js")
R.c("server/chunks/[root-of-the-server]__7daa31a4._.js")
R.c("server/chunks/[root-of-the-server]__6010f445._.js")
R.c("server/chunks/node_modules_next_f2da0d3e._.js")
R.c("server/chunks/_next-internal_server_app_api_reanswer_route_actions_10315fba.js")
R.m(45313)
module.exports=R.m(45313).exports
