var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/ai/test/route.js")
R.c("server/chunks/[root-of-the-server]__2d824759._.js")
R.c("server/chunks/_89166f1c._.js")
R.c("server/chunks/[root-of-the-server]__307c58c3._.js")
R.c("server/chunks/node_modules_next_f2da0d3e._.js")
R.c("server/chunks/[root-of-the-server]__4aa6c18e._.js")
R.c("server/chunks/[root-of-the-server]__0d030c0e._.js")
R.c("server/chunks/[root-of-the-server]__6010f445._.js")
R.c("server/chunks/node_modules_zod_v4_classic_external_fa90cebf.js")
R.c("server/chunks/_next-internal_server_app_api_ai_test_route_actions_d0a2f3b9.js")
R.m(23684)
module.exports=R.m(23684).exports
